#!/bin/bash

export CLASSPATH="$HADOOP_HOME/share/hadoop/mapreduce/hadoop-mapreduce-client-core-3.3.6.jar:$HADOOP_HOME/share/hadoop/mapreduce/mapreduce/hadoop-mapreduce-client-common-3.3.6.jar:$HADOOP_HOME/share/hadoop/common/hadoop-common-3.3.6.jar:~/tutorial1/SalesCountry/*:$HADOOP_HOME/lib/*"

echo javac ...
javac -d . SalesMapper.java SalesCountryReducer.java SalesCountryDriver.java
echo jar ...
jar cfm ProductSalePerCountry.jar Manifest.txt SalesCountry/*.class
#echo copy...
#$HADOOP_HOME/bin/hdfs dfs -copyFromLocal inputMapReduce /
#echo ls...
#$HADOOP_HOME/bin/hdfs dfs -ls /inputMapReduce
#echo rm...
#$HADOOP_HOME/bin/hdfs dfs -rm -R /mapreduce_output_sales
#echo start hadoop task...
#$HADOOP_HOME/bin/hadoop jar ProductSalePerCountry.jar /inputMapReduce /mapreduce_output_sales
#echo ls...
#$HADOOP_HOME/bin/hdfs dfs -ls /mapreduce_output_sales
#read -p "Press any key to continue - read the result data..."
#echo $HADOOP_HOME/bin/hdfs dfs -cat /mapreduce_output_sales/part-00000

